spring:
  security:
    user:
      name: user
      password: password
  datasource:
    url: jdbc:mysql://192.168.163.3:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 3100880856
logging:
  level:
    com.song: TRACE
server:
  servlet:
    encoding:
      charset: UTF-8